services:
  db:
    image: postgres:15-alpine
    container_name: pg-dev-2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresq1/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DIALECT=postgres
      - DB_SSL=false
    depends_on:
      - db

volumes:
  pgdata: