### Health Check
GET  http://localhost:3000/api/health

### Listar Usuarios
GET http://localhost:3000/api/users

### Criar Usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "nome": "Mariana Souza",
    "email": "mariana.souza@email.com",
    "password": "12345678"
}

### Buscar Usuário por Id
GET http://localhost:3000/api/users/1

### Atualizar Usuário
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "nome": "Mariana Souza Silva",
    "email": "mariana.silva@email.com"
}

### Excluir o Uusário
DELETE http://localhost:3000/api/users/1